# Generated by Django 5.2.1 on 2026-08-13 19:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('prison', '0010_region_prisonstation_region_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Leave Type Name')),
                ('is_maternity', models.BooleanField(default=False, verbose_name='Is Maternity Leave?')),
                ('is_study', models.BooleanField(default=False, verbose_name='Is Study Leave?')),
                ('default_days', models.IntegerField(blank=True, null=True, verbose_name='Default Days (if applicable)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('general_duties', 'General Duties'), ('medical_officer', 'Medical Officer'), ('female_in_charge', 'Female In-Charge'), ('administration', 'Administration'), ('accounts_office', 'Accounts Office'), ('research_office', 'Research Office'), ('gender', 'Gender Desk'), ('rehabilitation', 'Rehabilitation'), ('public_relations_office', 'Public Relations Office'), ('chaplaincy', 'Chaplaincy'), ('secretary', 'Secretary'), ('staff_officer', 'Staff Officer'), ('protocol', 'Protocol'), ('restorative_justice', 'Restorative Justice'), ('radio_communication', 'Radio Communication'), ('registry', 'Registry'), ('ict', 'ICT'), ('education', 'Education'), ('driver', 'Driver'), ('transport', 'Transport'), ('logistics', 'Logistics'), ('intelligence', 'Intelligence'), ('legal_office', 'Legal Office'), ('human_resources', 'Human Resources'), ('trainer/instructor', 'Trainer/Instructor'), ('disciplinary', 'Disciplinary'), ('procurement', 'Procurement'), ('audit', 'Audit'), ('stores', 'Stores'), ('gatekeeper', 'Gatekeeper'), ('station_officer', 'Station Officer'), ('station_hr', 'Station HR'), ('regional_commanding_officer', 'Regional Commanding Officer'), ('regional_headquarters_officer', 'Regional Headquarters Officer'), ('regional_hr', 'Regional HR'), ('commissioner_administration_and_human_resource', 'Commissioner of Admin'), ('commissioner_rehabilitation', 'Commissioner of Rehab'), ('commissioner_operations', 'Commissioner of Ops'), ('commissioner_training_school', 'Commissioner of Training School'), ('commissioner_correctional_services', 'Commissioner of Correctional Services'), ('director_of_farms', 'Director of Farms'), ('national_hr', 'National HR'), ('station_officer_in_charge', 'Station Officer (SO)'), ('general_duties_officer', 'General Duties Officer (GDO)'), ('disciplinary_officer', 'Disciplinary Officer (DO)'), ('messenger', 'Messenger'), ('watchman', 'Watchman'), ('farms', 'Farms'), ('finance_officer', 'Finance Officer'), ('male_in_charge', 'Male In-Charge'), ('hiv/aids_coordinator', 'HIV/AIDS Coordinator'), ('htc', 'HTC'), ('mental_health_officer', 'Mental Health Officer'), ('youth_officer', 'Youth Officer'), ('commandant', 'Commandant'), ('deputy_commandant', 'Deputy Commandant'), ('o/c_junior_training_school', 'Officer In-Charge of Junior Training School'), ('o/c_advance_training_school', 'Officer In-Charge of Advance Training School'), ('field_officer', 'Field Officer'), ('reception_officer', 'Reception Officer'), ('nutrition_officer', 'Nutritionist'), ('welfare_officer', 'Welfare Officer'), ('plumbing_officer', 'Plumbing Officer'), ('electrician_officer', 'Electrician Officer'), ('mechanical_officer', 'Mechanical Officer'), ('welder_officer', 'Welder Officer'), ('carpentry_officer', 'Carpentry Officer')], max_length=100, unique=True, verbose_name='Office Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Office Assignment',
                'verbose_name_plural': 'Office Assignments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Metric Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Performance Metric',
                'verbose_name_plural': 'Performance Metrics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('watchman', 'Watchman'), ('messenger', 'Messenger'), ('warder', 'Warder'), ('sergeant', 'Sergeant'), ('gaoler', 'Gaoler'), ('inspector', 'Inspector'), ('assistant_superintendent', 'Assistant Superintendent'), ('superintendent', 'Superintendent'), ('senior_superintendent', 'Senior Superintendent'), ('assistant_commissioner', 'Assistant Commissioner of Prison'), ('deputy_commissioner', 'Deputy Commissioner of Prison'), ('commissioner', 'Commissioner'), ('commissioner_general', 'Commissioner General')], max_length=50, unique=True, verbose_name='Rank Name')),
                ('leave_days_annual', models.IntegerField(default=24, verbose_name='Annual Leave Days')),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Ranks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('leave_request', 'Leave Request'), ('file_action', 'File Action'), ('disciplinary_action', 'Disciplinary Action'), ('promotion', 'Promotion'), ('transfer', 'Transfer'), ('system_alert', 'System Alert'), ('new_officer', 'New Officer Added')], max_length=50, verbose_name='Notification Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrms_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_hrms_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_picture', models.ImageField(blank=True, null=True, upload_to='officer_pictures/', verbose_name='Officer Picture')),
                ('service_number', models.CharField(help_text='Unique official service number.', max_length=50, unique=True, verbose_name='Service Number')),
                ('employment_number', models.CharField(blank=True, help_text='Internal government employment number.', max_length=50, null=True, unique=True, verbose_name='Employment Number')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Middle Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('date_joined_service', models.DateField(verbose_name='Date Joined Service')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender')),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('interdicted', 'Interdicted'), ('retired', 'Retired'), ('resigned', 'Resigned'), ('deceased', 'Deceased')], default='active', max_length=20, verbose_name='Current Status')),
                ('grade', models.CharField(blank=True, max_length=5, verbose_name='Grade')),
                ('contact_number', models.CharField(blank=True, max_length=20, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Official Email')),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='Village')),
                ('traditional_authority', models.CharField(blank=True, max_length=100, verbose_name='Traditional Authority (T/A)')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='District')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, verbose_name='Marital Status')),
                ('spouse_name', models.CharField(blank=True, max_length=200, verbose_name='Spouse Name')),
                ('number_of_children', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Children')),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200, verbose_name='Next of Kin Name')),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=100, verbose_name='Next of Kin Relationship')),
                ('next_of_kin_location', models.CharField(blank=True, max_length=255, verbose_name='Next of Kin Location')),
                ('next_of_kin_contact', models.CharField(blank=True, max_length=20, verbose_name='Next of Kin Contact')),
                ('notable_skills', models.TextField(blank=True, verbose_name='Notable Skills')),
                ('languages_spoken', models.TextField(blank=True, verbose_name='Languages Spoken')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_office_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_officers', to='hrms.officeassignment', verbose_name='Current Office Assignment')),
                ('prison_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='prison.prisonstation', verbose_name='Assigned Prison Station')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='prison.region', verbose_name='Assigned Region')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Associated User Account')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='hrms.rank', verbose_name='Current Rank')),
            ],
            options={
                'verbose_name': 'Officer',
                'verbose_name_plural': 'Officers',
                'ordering': ['surname', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('number_of_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Days')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='leave_documents/', verbose_name='Supporting Document')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('rejection_notes', models.TextField(blank=True, verbose_name='Rejection Notes')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved/Rejected At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approved/Rejected By')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hrms.leavetype', verbose_name='Leave Type')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hrms.officer', verbose_name='Officer')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255, verbose_name='Institution')),
                ('qualification', models.CharField(max_length=255, verbose_name='Qualification')),
                ('year_obtained', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Year Obtained')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='education_documents/', verbose_name='Supporting Document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='hrms.officer', verbose_name='Officer')),
            ],
            options={
                'verbose_name': 'Education Qualification',
                'verbose_name_plural': 'Education Qualifications',
                'ordering': ['-year_obtained'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_date', models.DateField(default=django.utils.timezone.now, verbose_name='Case Date')),
                ('offense', models.CharField(max_length=255, verbose_name='Offense')),
                ('description', models.TextField(verbose_name='Description')),
                ('action_taken', models.CharField(blank=True, choices=[('warning', 'Warning'), ('suspension', 'Suspension'), ('interdiction', 'Interdiction'), ('dismissal', 'Dismissal'), ('extra_duty', 'Extra duty')], max_length=50, verbose_name='Action Taken')),
                ('action_date', models.DateField(blank=True, null=True, verbose_name='Action Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_cases', to='hrms.officer', verbose_name='Officer')),
            ],
            options={
                'verbose_name': 'Disciplinary Case',
                'verbose_name_plural': 'Disciplinary Cases',
                'ordering': ['-case_date'],
            },
        ),
        migrations.CreateModel(
            name='OfficerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50, verbose_name='File Name')),
                ('file_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='File Number')),
                ('file_type', models.CharField(choices=[('letter_of_appointment', 'Letter of Appointment'), ('academic_certificate', 'Academic Certificate'), ('id_card', 'ID Card'), ('disciplinary_case', 'Disciplinary Case Document'), ('transfer_order', 'Transfer Order'), ('promotion_letter', 'Promotion Letter'), ('marriage_certificate', 'Marriage Certificate')], max_length=50, verbose_name='File Type')),
                ('document', models.FileField(upload_to='officer_documents/', verbose_name='Document File')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('action_to', models.CharField(blank=True, choices=[('national_commissioner', 'National Commissioner'), ('national_hr', 'National HR'), ('regional_commanding_officer', 'Regional Commanding Officer'), ('regional_headquarters_officer', 'Regional Headquarters Officer'), ('regional_hr', 'Regional HR'), ('station_officer_in_charge', 'Station Officer In-Charge'), ('station_officer', 'Station Officer'), ('station_hr', 'Station HR'), ('officer_self', 'Officer (Self)'), ('all', 'All Relevant Parties')], max_length=50, null=True, verbose_name='Action Required By Role')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('response_notes', models.TextField(blank=True, verbose_name='Response Notes')),
                ('action_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_for_action', to=settings.AUTH_USER_MODEL, verbose_name='Action Required By Specific User')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hrms.officer', verbose_name='Officer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Officer Document',
                'verbose_name_plural': 'Officer Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField(default=django.utils.timezone.now, verbose_name='Promotion Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='hrms.officer', verbose_name='Officer')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('new_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_to', to='hrms.rank', verbose_name='New Rank')),
                ('previous_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from', to='hrms.rank', verbose_name='Previous Rank')),
            ],
            options={
                'verbose_name': 'Promotion History',
                'verbose_name_plural': 'Promotion Histories',
                'ordering': ['-promotion_date'],
            },
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(default=django.utils.timezone.now, verbose_name='Transfer Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferred_to', to='prison.prisonstation', verbose_name='New Station')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='hrms.officer', verbose_name='Officer')),
                ('previous_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_from', to='prison.prisonstation', verbose_name='Previous Station')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
            ],
            options={
                'verbose_name': 'Transfer History',
                'verbose_name_plural': 'Transfer Histories',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('sick', 'Sick Leave'), ('official_duty', 'Official Duty')], max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hrms.officer', verbose_name='Officer')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
                'ordering': ['-date', 'officer__surname'],
                'unique_together': {('officer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AnnualLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('total_days_entitled', models.IntegerField(default=0, verbose_name='Total Days Entitled')),
                ('days_taken', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Days Taken')),
                ('last_reset_date', models.DateField(blank=True, null=True, verbose_name='Last Reset Date')),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annual_leave_balance', to='hrms.officer', verbose_name='Officer')),
            ],
            options={
                'verbose_name': 'Annual Leave Balance',
                'verbose_name_plural': 'Annual Leave Balances',
                'unique_together': {('officer', 'year')},
            },
        ),
        migrations.CreateModel(
            name='OfficerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of Record')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score (0-100)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='hrms.officer', verbose_name='Officer')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_entries', to='hrms.performancemetric', verbose_name='Metric')),
            ],
            options={
                'verbose_name': 'Officer Performance',
                'verbose_name_plural': 'Officer Performance',
                'ordering': ['-date', 'officer__surname'],
                'unique_together': {('officer', 'metric', 'date')},
            },
        ),
    ]
