# Generated by Django 5.2.1 on 2026-08-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_prisonstation_region_alter_customuser_is_locked_and_more'),
        ('hrms', '0002_trainingcourse_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='prison_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='accounts.prisonstation', verbose_name='Assigned Prison Station'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='accounts.region', verbose_name='Assigned Region'),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='new_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferred_to', to='accounts.prisonstation', verbose_name='New Station'),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='previous_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_from', to='accounts.prisonstation', verbose_name='Previous Station'),
        ),
    ]
