# Generated by Django 5.2.1 on 2026-09-03 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='document',
            field=models.FileField(blank=True, help_text='Attach PDF document (court orders, medical reports, etc.)', null=True, upload_to='prisoner_documents/'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='fingerprint_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='fingerprint_captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_fingerprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='fingerprint_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of fingerprint for quick matching', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='fingerprint_quality',
            field=models.IntegerField(blank=True, help_text='Quality score 0-100', null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='fingerprint_template',
            field=models.TextField(blank=True, help_text='Base64 encoded fingerprint template', null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='first_incarceration_date',
            field=models.DateField(blank=True, help_text='Date of first incarceration (if recidivist)', null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='identity_verification_notes',
            field=models.TextField(blank=True, help_text='Notes about identity verification process'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='identity_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='identity_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_identities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='is_identity_verified',
            field=models.BooleanField(default=False, help_text='Indicates if identity has been verified via fingerprint'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='is_recidivist',
            field=models.BooleanField(default=False, help_text='Indicates if this prisoner has been incarcerated before'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='previous_identities',
            field=models.ManyToManyField(blank=True, related_name='linked_identities', to='prison.prisoner'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='previous_prisoner_numbers',
            field=models.TextField(blank=True, help_text='Comma-separated list of previous prisoner numbers'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='recidivism_detected_at',
            field=models.DateTimeField(blank=True, help_text='When recidivism was detected', null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='recidivism_detected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_recidivists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='recidivism_notes',
            field=models.TextField(blank=True, help_text='Notes about recidivism detection'),
        ),
        migrations.AddField(
            model_name='prisonstation',
            name='region',
            field=models.CharField(choices=[('southern', 'Southern Region'), ('northern', 'Northern Region'), ('eastern', 'Eastern Region'), ('central', 'Central Region')], default='southern', max_length=10),
        ),
        migrations.AddField(
            model_name='rationconsumption',
            name='is_auto_calculated',
            field=models.BooleanField(default=False, help_text='Whether this consumption was automatically calculated based on prisoner count'),
        ),
        migrations.AddField(
            model_name='rationitem',
            name='daily_consumption_per_prisoner_kg',
            field=models.DecimalField(decimal_places=4, default=0.5, help_text='Daily consumption per prisoner in kg (used for automatic calculations)', max_digits=10),
        ),
        migrations.AddField(
            model_name='rationitem',
            name='estimated_days_remaining',
            field=models.PositiveIntegerField(default=0, help_text='Estimated days ration will last based on current stock and prisoner count'),
        ),
        migrations.AddField(
            model_name='rationitem',
            name='last_consumption_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rationitem',
            name='last_stock_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('transfer', 'Transfer'), ('approve', 'Approve'), ('login', 'Login'), ('logout', 'Logout'), ('add_item', 'Add Item'), ('withdraw_money', 'Withdraw Money'), ('collect_item', 'Collect Item'), ('capture_fingerprint', 'Capture Fingerprint'), ('verify_identity', 'Verify Identity'), ('fingerprint_match', 'Fingerprint Match'), ('link_identity', 'Link Identity')], max_length=30),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.CreateModel(
            name='FingerprintDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('integrated', 'Integrated (Laptop)'), ('usb', 'USB Scanner'), ('mobile', 'Mobile Scanner'), ('other', 'Other')], default='integrated', max_length=20)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='active', max_length=20)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('prison_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_devices', to='prison.prisonstation')),
            ],
            options={
                'verbose_name': 'Fingerprint Device',
                'verbose_name_plural': 'Fingerprint Devices',
                'ordering': ['prison_station', 'name'],
            },
        ),
        migrations.AddField(
            model_name='prisoner',
            name='fingerprint_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_fingerprints', to='prison.fingerprintdevice'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('medical_checkup', 'Medical Checkup Reminder'), ('near_release', 'Prisoner Near Release'), ('new_admission', 'New Prisoner Admission'), ('general', 'General Notification')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_required', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='prison.medicalrecord')),
                ('prisoner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='prison.prisoner')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrisonerReleaseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_role', models.CharField(choices=[('officer_in_charge', 'Officer in Charge'), ('station_officer', 'Station Officer')], max_length=25)),
                ('release_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('prisoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_reviews', to='prison.prisoner')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_release_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_release_reviews', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_reviews', to='prison.prisonstation')),
            ],
        ),
        migrations.CreateModel(
            name='FingerprintAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('capture', 'Fingerprint Capture'), ('verify', 'Identity Verification'), ('search', 'Fingerprint Search'), ('match', 'Fingerprint Match'), ('link', 'Identity Link'), ('unlink', 'Identity Unlink'), ('delete', 'Fingerprint Delete'), ('update', 'Fingerprint Update')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prisoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_audits', to='prison.prisoner')),
            ],
            options={
                'verbose_name': 'Fingerprint Audit Log',
                'verbose_name_plural': 'Fingerprint Audit Logs',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['prisoner', '-performed_at'], name='prison_fing_prisone_f3b407_idx'), models.Index(fields=['operation', '-performed_at'], name='prison_fing_operati_d743f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='FingerprintMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Match confidence score 0-100')),
                ('match_status', models.CharField(choices=[('exact', 'Exact Match'), ('probable', 'Probable Match'), ('potential', 'Potential Match'), ('no_match', 'No Match'), ('error', 'Match Error')], max_length=20)),
                ('search_timestamp', models.DateTimeField(auto_now_add=True)),
                ('search_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('match_details', models.TextField(blank=True)),
                ('matched_prisoner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_fingerprints', to='prison.prisoner')),
                ('searched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('searched_prisoner', models.ForeignKey(blank=True, help_text='The prisoner whose fingerprint was used for search (null for unknown)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searched_fingerprints', to='prison.prisoner')),
            ],
            options={
                'verbose_name': 'Fingerprint Match',
                'verbose_name_plural': 'Fingerprint Matches',
                'ordering': ['-search_timestamp'],
                'indexes': [models.Index(fields=['searched_prisoner', '-search_timestamp'], name='prison_fing_searche_e7ff56_idx'), models.Index(fields=['matched_prisoner', '-search_timestamp'], name='prison_fing_matched_353b25_idx'), models.Index(fields=['match_status'], name='prison_fing_match_s_d78d77_idx')],
            },
        ),
    ]
