# Generated by Django 5.2.1 on 2026-08-03 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='fingerprint_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='fingerprint_captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_fingerprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='fingerprint_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of fingerprint for quick matching', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='fingerprint_quality',
            field=models.IntegerField(blank=True, help_text='Quality score 0-100', null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='fingerprint_template',
            field=models.TextField(blank=True, help_text='Base64 encoded fingerprint template', null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='identity_verification_notes',
            field=models.TextField(blank=True, help_text='Notes about identity verification process'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='identity_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='identity_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_identities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='is_identity_verified',
            field=models.BooleanField(default=False, help_text='Indicates if identity has been verified via fingerprint'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='previous_identities',
            field=models.ManyToManyField(blank=True, related_name='linked_identities', to='prison.prisoner'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('transfer', 'Transfer'), ('approve', 'Approve'), ('login', 'Login'), ('logout', 'Logout'), ('add_item', 'Add Item'), ('withdraw_money', 'Withdraw Money'), ('collect_item', 'Collect Item'), ('capture_fingerprint', 'Capture Fingerprint'), ('verify_identity', 'Verify Identity'), ('fingerprint_match', 'Fingerprint Match'), ('link_identity', 'Link Identity')], max_length=30),
        ),
        migrations.CreateModel(
            name='FingerprintDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('integrated', 'Integrated (Laptop)'), ('usb', 'USB Scanner'), ('mobile', 'Mobile Scanner'), ('other', 'Other')], default='integrated', max_length=20)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='active', max_length=20)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('prison_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_devices', to='prison.prisonstation')),
            ],
            options={
                'verbose_name': 'Fingerprint Device',
                'verbose_name_plural': 'Fingerprint Devices',
                'ordering': ['prison_station', 'name'],
            },
        ),
        migrations.AddField(
            model_name='prisoner',
            name='fingerprint_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_fingerprints', to='prison.fingerprintdevice'),
        ),
        migrations.CreateModel(
            name='FingerprintAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('capture', 'Fingerprint Capture'), ('verify', 'Identity Verification'), ('search', 'Fingerprint Search'), ('match', 'Fingerprint Match'), ('link', 'Identity Link'), ('unlink', 'Identity Unlink'), ('delete', 'Fingerprint Delete'), ('update', 'Fingerprint Update')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the operation as JSON')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prisoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_audits', to='prison.prisoner')),
            ],
            options={
                'verbose_name': 'Fingerprint Audit Log',
                'verbose_name_plural': 'Fingerprint Audit Logs',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['prisoner', '-performed_at'], name='prison_fing_prisone_f3b407_idx'), models.Index(fields=['operation', '-performed_at'], name='prison_fing_operati_d743f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='FingerprintMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Match confidence score 0-100')),
                ('match_status', models.CharField(choices=[('exact', 'Exact Match'), ('probable', 'Probable Match'), ('potential', 'Potential Match'), ('no_match', 'No Match'), ('error', 'Match Error')], max_length=20)),
                ('search_timestamp', models.DateTimeField(auto_now_add=True)),
                ('search_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('match_details', models.TextField(blank=True)),
                ('matched_prisoner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_fingerprints', to='prison.prisoner')),
                ('searched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('searched_prisoner', models.ForeignKey(blank=True, help_text='The prisoner whose fingerprint was used for search (null for unknown)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searched_fingerprints', to='prison.prisoner')),
            ],
            options={
                'verbose_name': 'Fingerprint Match',
                'verbose_name_plural': 'Fingerprint Matches',
                'ordering': ['-search_timestamp'],
                'indexes': [models.Index(fields=['searched_prisoner', '-search_timestamp'], name='prison_fing_searche_e7ff56_idx'), models.Index(fields=['matched_prisoner', '-search_timestamp'], name='prison_fing_matched_353b25_idx'), models.Index(fields=['match_status'], name='prison_fing_match_s_d78d77_idx')],
            },
        ),
    ]
