# Generated by Django 5.2.1 on 2026-08-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0002_prisoner_fingerprint_captured_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintauditlog',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='fingerprintauditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
