# Generated by Django 5.2.1 on 2026-09-06 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prison", "0002_prisoner_document_prisoner_fingerprint_captured_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("RELEASE", "Release"),
                            ("TRANSFER", "Transfer"),
                            ("SENTENCE_CHANGE", "Sentence Change"),
                            ("DATE_CHANGE", "Date Change"),
                            ("PERMISSION_CHANGE", "Permission Change"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("FORWARD", "Forward"),
                            ("IMPORT", "Import"),
                            ("EXPORT", "Export"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=50)),
                ("object_id", models.CharField(blank=True, max_length=50)),
                ("object_repr", models.CharField(blank=True, max_length=200)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("request_path", models.CharField(blank=True, max_length=200)),
                ("session_id", models.CharField(blank=True, max_length=40)),
                (
                    "prison_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_trails",
                        to="prison.prisonstation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_trails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PrisonerAuditHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("change_reason", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prisoner_audit_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prisoner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_history",
                        to="prison.prisoner",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="ReleaseAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=20)),
                ("original_release_date", models.DateField(blank=True, null=True)),
                ("modified_release_date", models.DateField(blank=True, null=True)),
                ("original_sentence", models.FloatField(blank=True, null=True)),
                ("modified_sentence", models.FloatField(blank=True, null=True)),
                ("review_role", models.CharField(blank=True, max_length=30)),
                ("approval_status", models.CharField(blank=True, max_length=20)),
                ("change_reason", models.TextField(blank=True)),
                ("risk_flags", models.JSONField(blank=True, default=dict)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="release_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prisoner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_audit_logs",
                        to="prison.prisoner",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="SentryAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("date_manipulation", "Date Manipulation"),
                            ("sentence_reduction", "Unexplained Sentence Reduction"),
                            ("early_release", "Early Release Detected"),
                            ("unauthorized_access", "Unauthorized Access"),
                            ("multiple_changes", "Multiple Changes in Short Period"),
                            ("off_hours_access", "Off-hours Access"),
                            ("foreign_ip", "Foreign IP Address"),
                            ("privilege_escalation", "Privilege Escalation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "audit_trail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sentry_alerts",
                        to="prison.audittrail",
                    ),
                ),
                (
                    "prisoner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentry_alerts",
                        to="prison.prisoner",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_sentry_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sentry_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["timestamp"], name="prison_audi_timesta_6bda65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["user", "-timestamp"], name="prison_audi_user_id_de594d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["model_name", "object_id"],
                name="prison_audi_model_n_112a58_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(fields=["action"], name="prison_audi_action_5bff14_idx"),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["severity"], name="prison_audi_severit_3e3705_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prisoneraudithistory",
            index=models.Index(
                fields=["prisoner", "-changed_at"],
                name="prison_pris_prisone_19d3b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="releaseauditlog",
            index=models.Index(
                fields=["prisoner", "-performed_at"],
                name="prison_rele_prisone_f23bc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sentryalert",
            index=models.Index(
                fields=["alert_type"], name="prison_sent_alert_t_922624_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentryalert",
            index=models.Index(
                fields=["severity"], name="prison_sent_severit_516b69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentryalert",
            index=models.Index(
                fields=["is_resolved"], name="prison_sent_is_reso_afeccd_idx"
            ),
        ),
    ]
