# Generated by Django 5.2.1 on 2026-09-06 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prison", "0003_audittrail_prisoneraudithistory_releaseauditlog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prisoner",
            name="prisoner_number",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated prisoner number. Leave blank to auto-generate.",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="PrisonerNumberCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prisoner_class",
                    models.CharField(
                        choices=[("convicted", "Convicted"), ("remand", "Remand")],
                        max_length=10,
                    ),
                ),
                ("year", models.IntegerField()),
                ("last_number", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prison_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="number_counters",
                        to="prison.prisonstation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prisoner Number Counter",
                "verbose_name_plural": "Prisoner Number Counters",
                "ordering": ["prison_station", "prisoner_class", "-year"],
                "unique_together": {("prison_station", "prisoner_class", "year")},
            },
        ),
    ]
