# Generated by Django 5.2.1 on 2026-08-03 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0003_alter_fingerprintauditlog_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='first_incarceration_date',
            field=models.DateField(blank=True, help_text='Date of first incarceration (if recidivist)', null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='is_recidivist',
            field=models.BooleanField(default=False, help_text='Indicates if this prisoner has been incarcerated before'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='previous_prisoner_numbers',
            field=models.TextField(blank=True, help_text='Comma-separated list of previous prisoner numbers'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='recidivism_detected_at',
            field=models.DateTimeField(blank=True, help_text='When recidivism was detected', null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='recidivism_detected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_recidivists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='recidivism_notes',
            field=models.TextField(blank=True, help_text='Notes about recidivism detection'),
        ),
    ]
