# Generated by Django 5.2.1 on 2026-08-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0004_prisoner_first_incarceration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='document',
            field=models.FileField(blank=True, help_text='Attach PDF document (court orders, medical reports, etc.)', null=True, upload_to='prisoner_documents/'),
        ),
    ]
