# Generated by Django 5.2.1 on 2026-09-07 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0005_convictedprisoner_case_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrisonerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='prisoner_attachments/')),
                ('attachment_type', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prisoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='prison.prisoner')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
