# Generated by Django 5.2.1 on 2026-08-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0005_prisoner_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationconsumption',
            name='is_auto_calculated',
            field=models.BooleanField(default=False, help_text='Whether this consumption was automatically calculated based on prisoner count'),
        ),
        migrations.AddField(
            model_name='rationitem',
            name='daily_consumption_per_prisoner_kg',
            field=models.DecimalField(decimal_places=4, default=0.5, help_text='Daily consumption per prisoner in kg (used for automatic calculations)', max_digits=10),
        ),
        migrations.AddField(
            model_name='rationitem',
            name='estimated_days_remaining',
            field=models.PositiveIntegerField(default=0, help_text='Estimated days ration will last based on current stock and prisoner count'),
        ),
        migrations.AddField(
            model_name='rationitem',
            name='last_consumption_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rationitem',
            name='last_stock_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
