# Generated by Django 5.2.1 on 2026-08-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0006_rationconsumption_is_auto_calculated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisonstation',
            name='region',
            field=models.CharField(choices=[('southern', 'Southern Region'), ('northern', 'Northern Region'), ('eastern', 'Eastern Region'), ('western', 'Western Region')], default='southern', max_length=10),
        ),
    ]
