# Generated by Django 5.2.1 on 2026-08-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0010_region_prisonstation_region_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
