# Generated by Django 5.2.1 on 2026-08-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_prisonstation_region_alter_customuser_is_locked_and_more'),
        ('hrms', '0003_alter_officer_prison_station_alter_officer_region_and_more'),
        ('prison', '0011_alter_region_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prisonstation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='prisonstation',
            name='region',
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='prison_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.prisonstation'),
        ),
        migrations.AlterField(
            model_name='prisonertransfer',
            name='to_prison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='accounts.prisonstation'),
        ),
        migrations.AlterField(
            model_name='fingerprintdevice',
            name='prison_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_devices', to='accounts.prisonstation'),
        ),
        migrations.AlterField(
            model_name='prisonertransfer',
            name='from_prison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='accounts.prisonstation'),
        ),
        migrations.AlterField(
            model_name='prisonerreleasereview',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_reviews', to='accounts.prisonstation'),
        ),
        migrations.AlterField(
            model_name='rationitem',
            name='prison_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ration_items', to='accounts.prisonstation'),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='PrisonStation',
        ),
    ]
