# Generated by Django 5.2.1 on 2026-08-31 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_prisonstation_region_alter_customuser_is_locked_and_more'),
        ('prison', '0012_remove_prisonstation_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InmateReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('return_type', models.CharField(choices=[('convicted', 'Convicted Inmates Return'), ('discharge', 'Due Discharge'), ('lockup', 'Lockup Summary'), ('monthly', 'Monthly Report'), ('quarterly', 'Quarterly Report'), ('annual', 'Annual Report'), ('other', 'Other Return')], max_length=20)),
                ('month', models.IntegerField(blank=True, help_text='Month (1-12)', null=True)),
                ('year', models.IntegerField(blank=True, help_text='Year', null=True)),
                ('file', models.FileField(upload_to='inmate_returns/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_type', models.CharField(blank=True, help_text='File extension/type', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmate_returns', to='accounts.prisonstation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inmate Return',
                'verbose_name_plural': 'Inmate Returns',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['station', '-uploaded_at'], name='prison_inma_station_2fbcec_idx'), models.Index(fields=['return_type', '-uploaded_at'], name='prison_inma_return__fae01b_idx'), models.Index(fields=['status'], name='prison_inma_status_a07aee_idx'), models.Index(fields=['month', 'year'], name='prison_inma_month_bc30a2_idx')],
            },
        ),
    ]
