# Generated by Django 5.2.1 on 2026-08-31 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_prisonstation_region_alter_customuser_is_locked_and_more'),
        ('prison', '0013_inmatereturn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InmateReturnData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField(default=0)),
                ('prisoner_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('sex', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, db_index=True, null=True)),
                ('offense', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('chief', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('court', models.CharField(blank=True, max_length=100, null=True)),
                ('case_no', models.CharField(blank=True, max_length=100, null=True)),
                ('sentence_months', models.FloatField(blank=True, null=True)),
                ('date_of_committal', models.DateField(blank=True, null=True)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('date_of_conviction', models.DateField(blank=True, null=True)),
                ('release_date_without_remission', models.DateField(blank=True, null=True)),
                ('release_date_with_remission', models.DateField(blank=True, null=True)),
                ('expected_date_release', models.DateField(blank=True, null=True)),
                ('arresting_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('last_court_appearance', models.DateField(blank=True, null=True)),
                ('judge_name', models.CharField(blank=True, max_length=100, null=True)),
                ('case_status', models.CharField(blank=True, max_length=100, null=True)),
                ('pre_trial_period', models.CharField(blank=True, max_length=50, null=True)),
                ('sentence_served', models.CharField(blank=True, max_length=50, null=True)),
                ('amnesty_earned', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_conviction_particulars', models.TextField(blank=True, null=True)),
                ('conduct', models.CharField(blank=True, max_length=50, null=True)),
                ('child_name', models.CharField(blank=True, max_length=200, null=True)),
                ('child_age', models.IntegerField(blank=True, null=True)),
                ('child_sex', models.CharField(blank=True, max_length=10, null=True)),
                ('gestation_period', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('row_number', models.IntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Inmate Return Data',
                'verbose_name_plural': 'Inmate Return Data',
                'ordering': ['inmate_return', 'serial_no', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='ReturnTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('return_type', models.CharField(choices=[('convicted', 'Convicted Inmates Return'), ('remanded', 'Remanded Inmates Return'), ('remand_murder', 'Remanded Murder Cases Return'), ('convicted_foreigners', 'Convicted Foreigners Return'), ('foreigners_remand', 'Foreigners Remand Return'), ('general_remandees', 'General Remandees Return'), ('chronically_ill', 'Chronically Ill Inmates Return'), ('convicted_elderly', 'Convicted Elderly (70 yrs & above)'), ('convicted_pregnant', 'Convicted Pregnant Inmates'), ('discharged_after_reductions', 'Discharged After Effecting Months Reduction'), ('children_with_mothers', 'Children Accompanying Their Mothers'), ('convicted_pregnant_mothers', 'Convicted Pregnant Mothers'), ('remand_pregnant_mothers_murder', 'Remandees Pregnant Mothers on Homicide'), ('children_with_mothers_homicide', 'Children Accompanying Mothers on Homicide'), ('pending_cases', 'Pending Cases Return'), ('due_discharge', 'Due Discharge'), ('lockup_summary', 'Lockup Summary'), ('quarterly', 'Quarterly Report'), ('annual', 'Annual Report'), ('monthly_statistics', 'Monthly Statistics'), ('weekly_summary', 'Weekly Summary'), ('special', 'Special Return'), ('other', 'Other Return')], db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('columns', models.JSONField(default=list, help_text='List of column definitions with key, header, and type')),
                ('sample_data', models.JSONField(blank=True, default=list, help_text='Sample data for template')),
                ('column_groups', models.JSONField(blank=True, default=dict, help_text='Group columns for display purposes')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default template for this type')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Return Template',
                'verbose_name_plural': 'Return Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='inmatereturn',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inmate Return', 'verbose_name_plural': 'Inmate Returns'},
        ),
        migrations.RemoveIndex(
            model_name='inmatereturn',
            name='prison_inma_station_2fbcec_idx',
        ),
        migrations.RemoveIndex(
            model_name='inmatereturn',
            name='prison_inma_return__fae01b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='inmatereturn',
            unique_together={('station', 'return_type', 'month', 'year')},
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='age_distribution',
            field=models.JSONField(blank=True, default=dict, help_text='Age distribution statistics'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Notes from the approver'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the return was approved', null=True),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to review this return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the return was marked as completed', null=True),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who marked the return as completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this return was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='csv_imported_at',
            field=models.DateTimeField(blank=True, help_text='When CSV data was imported', null=True),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='csv_imported_by',
            field=models.ForeignKey(blank=True, help_text='User who imported the CSV data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_csv_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='csv_row_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of rows imported from CSV'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Custom fields for additional data'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='description',
            field=models.TextField(blank=True, help_text='Optional detailed description of the return'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for custom date ranges', null=True),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='female_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of female prisoners'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the file for integrity checking', max_length=64),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='file_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When the file was uploaded', null=True),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='has_csv_data',
            field=models.BooleanField(default=False, help_text='Whether this return has imported CSV data'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes for staff (not shown to external users)'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this return is publicly visible'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Whether this return can be used as a template'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, help_text='When this return was last accessed', null=True),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='male_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of male prisoners'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='offense_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Breakdown of offenses with counts'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Region of the station (auto-populated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmate_returns', to='accounts.region'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When the return was rejected', null=True),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='User who rejected the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='reporting_period',
            field=models.CharField(blank=True, help_text="Description of reporting period (e.g., 'Q1 2026', 'January 2026')", max_length=100),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='review_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for review/approval', null=True),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date for custom date ranges', null=True),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='status_history',
            field=models.JSONField(blank=True, default=list, help_text='History of status changes with timestamps and users'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the return was submitted for approval', null=True),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='summary_data',
            field=models.JSONField(blank=True, default=dict, help_text='Comprehensive summary data for the return'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for categorization and search'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='total_records',
            field=models.PositiveIntegerField(default=0, help_text='Total number of records in this return'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='unique_prisoners',
            field=models.PositiveIntegerField(default=0, help_text='Number of unique prisoners in the return'),
        ),
        migrations.AddField(
            model_name='inmatereturn',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number of this return'),
        ),
        migrations.AlterField(
            model_name='inmatereturn',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded file (PDF, Word, Excel, CSV, etc.)', null=True, upload_to='inmate_returns/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='inmatereturn',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original file name', max_length=255),
        ),
        migrations.AlterField(
            model_name='inmatereturn',
            name='month',
            field=models.IntegerField(blank=True, help_text='Month (1-12) for period-specific returns', null=True),
        ),
        migrations.AlterField(
            model_name='inmatereturn',
            name='remarks',
            field=models.TextField(blank=True, help_text='General remarks or notes about this return'),
        ),
        migrations.AlterField(
            model_name='inmatereturn',
            name='return_type',
            field=models.CharField(choices=[('convicted', 'Convicted Inmates Return'), ('remanded', 'Remanded Inmates Return'), ('remand_murder', 'Remanded Murder Cases Return'), ('convicted_foreigners', 'Convicted Foreigners Return'), ('foreigners_remand', 'Foreigners Remand Return'), ('general_remandees', 'General Remandees Return'), ('chronically_ill', 'Chronically Ill Inmates Return'), ('convicted_elderly', 'Convicted Elderly (70 yrs & above)'), ('convicted_pregnant', 'Convicted Pregnant Inmates'), ('discharged_after_reductions', 'Discharged After Effecting Months Reduction'), ('children_with_mothers', 'Children Accompanying Their Mothers'), ('convicted_pregnant_mothers', 'Convicted Pregnant Mothers'), ('remand_pregnant_mothers_murder', 'Remandees Pregnant Mothers on Homicide'), ('children_with_mothers_homicide', 'Children Accompanying Mothers on Homicide'), ('pending_cases', 'Pending Cases Return'), ('due_discharge', 'Due Discharge'), ('lockup_summary', 'Lockup Summary'), ('quarterly', 'Quarterly Report'), ('annual', 'Annual Report'), ('monthly_statistics', 'Monthly Statistics'), ('weekly_summary', 'Weekly Summary'), ('special', 'Special Return'), ('other', 'Other Return')], help_text='Type of return being generated', max_length=50),
        ),
        migrations.AlterField(
            model_name='inmatereturn',
            name='station',
            field=models.ForeignKey(help_text='Prison station that this return belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='inmate_returns', to='accounts.prisonstation'),
        ),
        migrations.AlterField(
            model_name='inmatereturn',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('processing', 'Processing'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='inmatereturn',
            name='title',
            field=models.CharField(help_text="Descriptive title for the return (e.g., 'Convicted Inmates Return - Zomba - November 2026')", max_length=300),
        ),
        migrations.AlterField(
            model_name='inmatereturn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this return was last updated'),
        ),
        migrations.AlterField(
            model_name='inmatereturn',
            name='year',
            field=models.IntegerField(blank=True, help_text='Year for period-specific returns', null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='category',
            field=models.CharField(choices=[('routine', 'Routine Checkup'), ('emergency', 'Emergency'), ('chronic', 'Chronic Condition'), ('mental', 'Mental Health'), ('dental', 'Dental')], max_length=20),
        ),
        migrations.AlterField(
            model_name='physicalcharacteristics',
            name='eyes_color',
            field=models.CharField(choices=[('brown', 'Brown'), ('black', 'Black'), ('blue', 'Blue'), ('green', 'Green')], max_length=20),
        ),
        migrations.AlterField(
            model_name='physicalcharacteristics',
            name='health_status',
            field=models.CharField(choices=[('none', 'None'), ('tb', 'TB'), ('hiv', 'HIV'), ('malaria', 'Malaria prone'), ('ptsd', 'PTSD'), ('stis', 'STIs'), ('malnutrition', 'Malnutrition')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='prisonerparticulars',
            name='nationality',
            field=models.CharField(choices=[('malawian', 'Malawian'), ('mozambican', 'Mozambican'), ('zimbabwean', 'Zimbabwean'), ('congolese', 'Congolese'), ('zambian', 'Zambian'), ('tanzanian', 'Tanzanian'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('indian', 'Indian'), ('british', 'British'), ('south_african', 'South African'), ('burundi', 'Burundi'), ('rwandan', 'Rwandan'), ('botswana', 'Botswana')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prisonerparticulars',
            name='religion',
            field=models.CharField(choices=[('christian', 'Christian'), ('muslim', 'Muslim')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='relationship',
            field=models.CharField(choices=[('family', 'Family Member'), ('friend', 'Friend'), ('lawyer', 'Lawyer'), ('official', 'Government Official')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='inmatereturn',
            index=models.Index(fields=['station', '-created_at'], name='prison_inma_station_842758_idx'),
        ),
        migrations.AddIndex(
            model_name='inmatereturn',
            index=models.Index(fields=['return_type', '-created_at'], name='prison_inma_return__ed09e9_idx'),
        ),
        migrations.AddIndex(
            model_name='inmatereturn',
            index=models.Index(fields=['submitted_at'], name='prison_inma_submitt_ec1783_idx'),
        ),
        migrations.AddIndex(
            model_name='inmatereturn',
            index=models.Index(fields=['approved_at'], name='prison_inma_approve_2accce_idx'),
        ),
        migrations.AddIndex(
            model_name='inmatereturn',
            index=models.Index(fields=['created_by'], name='prison_inma_created_e8a46d_idx'),
        ),
        migrations.AddIndex(
            model_name='inmatereturn',
            index=models.Index(fields=['assigned_to'], name='prison_inma_assigne_64285e_idx'),
        ),
        migrations.AddField(
            model_name='inmatereturndata',
            name='inmate_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_rows', to='prison.inmatereturn'),
        ),
        migrations.AddField(
            model_name='returntemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='inmatereturn',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='inmatereturn',
            name='uploaded_by',
        ),
        migrations.AddIndex(
            model_name='inmatereturndata',
            index=models.Index(fields=['inmate_return', 'prisoner_number'], name='prison_inma_inmate__37dc63_idx'),
        ),
        migrations.AddIndex(
            model_name='inmatereturndata',
            index=models.Index(fields=['inmate_return', 'serial_no'], name='prison_inma_inmate__2bc7f2_idx'),
        ),
        migrations.AddIndex(
            model_name='inmatereturndata',
            index=models.Index(fields=['inmate_return', 'full_name'], name='prison_inma_inmate__326a52_idx'),
        ),
        migrations.AddIndex(
            model_name='inmatereturndata',
            index=models.Index(fields=['inmate_return', 'offense'], name='prison_inma_inmate__229136_idx'),
        ),
        migrations.AddIndex(
            model_name='inmatereturndata',
            index=models.Index(fields=['inmate_return', 'sex'], name='prison_inma_inmate__b5c0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='inmatereturndata',
            index=models.Index(fields=['inmate_return', 'nationality'], name='prison_inma_inmate__b4b220_idx'),
        ),
        migrations.AddIndex(
            model_name='inmatereturndata',
            index=models.Index(fields=['inmate_return', 'district'], name='prison_inma_inmate__340ac1_idx'),
        ),
    ]
