# Generated by Django 5.2.1 on 2026-09-03 07:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prison', '0002_prisoner_document_prisoner_fingerprint_captured_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('convicted_inmates', 'Convicted Inmates'), ('due_discharge', 'Due Discharge'), ('remand_murder', 'Remand Murder Prisoners'), ('convicted_foreigners', 'Convicted Foreigners'), ('general_remand', 'General Remandees'), ('pardon_consideration', 'Pardon Consideration'), ('chronically_ill', 'Chronically Ill Convicted'), ('elderly_inmates', 'Elderly Inmates (70+)'), ('discharged_reduction', 'Discharged After Reduction'), ('children_with_mothers', 'Children Accompanying Mothers'), ('pregnant_convicted', 'Pregnant Convicted'), ('pregnant_remand', 'Pregnant Remand'), ('children_remand', 'Children with Mothers on Remand'), ('foreigners_remand', 'Foreigners on Remand')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='return_templates/', validators=[django.core.validators.FileExtensionValidator(['csv', 'xlsx', 'xls'])])),
                ('required_columns', models.JSONField(default=list, help_text='List of required column headers')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReturnSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='return_submissions/', validators=[django.core.validators.FileExtensionValidator(['csv', 'xlsx', 'xls'])])),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('imported', 'Imported Successfully')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('prison_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_submissions', to='prison.prisonstation')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_submissions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='returns.returntemplate')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_data', models.JSONField(default=dict)),
                ('prisoner_number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('offense', models.CharField(blank=True, max_length=300)),
                ('court_case_number', models.CharField(blank=True, max_length=100)),
                ('sentence', models.CharField(blank=True, max_length=100)),
                ('date_of_committal', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_rows', to='returns.returnsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegionalReturnSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('period', models.CharField(max_length=20)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('male_count', models.PositiveIntegerField(default=0)),
                ('female_count', models.PositiveIntegerField(default=0)),
                ('additional_data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('category', 'region', 'period', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='StationReturnStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='e.g., 2026-11 for November 2026', max_length=20)),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prison_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_statuses', to='prison.prisonstation')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='returns.returnsubmission')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_statuses', to='returns.returntemplate')),
            ],
            options={
                'ordering': ['prison_station', 'template__category'],
                'unique_together': {('prison_station', 'template', 'period')},
            },
        ),
    ]
