# Generated by Django 5.2.1 on 2026-09-03 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0002_prisoner_document_prisoner_fingerprint_captured_at_and_more'),
        ('returns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySubmissionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('period', models.CharField(max_length=20)),
                ('total_required', models.PositiveIntegerField(default=0)),
                ('total_submitted', models.PositiveIntegerField(default=0)),
                ('total_approved', models.PositiveIntegerField(default=0)),
                ('total_rejected', models.PositiveIntegerField(default=0)),
                ('total_pending', models.PositiveIntegerField(default=0)),
                ('template_statuses', models.JSONField(default=dict, help_text='JSON dict of template category statuses')),
                ('is_complete', models.BooleanField(default=False, help_text='Indicates if all required returns are submitted')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'prison_station__name'],
            },
        ),
        migrations.CreateModel(
            name='ReturnTypeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('period', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Submission'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['prison_station', 'template__category', 'year', 'month'],
            },
        ),
        migrations.AlterModelOptions(
            name='stationreturnstatus',
            options={'ordering': ['prison_station', 'template__category', 'year', 'month']},
        ),
        migrations.AddField(
            model_name='regionalreturnsummary',
            name='month',
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='regionalreturnsummary',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='returnsubmission',
            name='month',
            field=models.PositiveIntegerField(default=9, help_text='Reporting month (1-12)'),
        ),
        migrations.AddField(
            model_name='returnsubmission',
            name='period',
            field=models.CharField(default='2026-09', help_text='Reporting period (YYYY-MM)', max_length=20),
        ),
        migrations.AddField(
            model_name='returnsubmission',
            name='total_female',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='returnsubmission',
            name='total_male',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='returnsubmission',
            name='year',
            field=models.PositiveIntegerField(default=2026, help_text='Reporting year (e.g., 2026)'),
        ),
        migrations.AddField(
            model_name='returntemplate',
            name='column_headers',
            field=models.JSONField(default=list, help_text='Display headers for the template'),
        ),
        migrations.AddField(
            model_name='returntemplate',
            name='example_data',
            field=models.JSONField(default=list, help_text='Example rows for reference'),
        ),
        migrations.AddField(
            model_name='returntemplate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Indicates if this is a system default template'),
        ),
        migrations.AddField(
            model_name='stationreturnstatus',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the return was approved', null=True),
        ),
        migrations.AddField(
            model_name='stationreturnstatus',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for submission', null=True),
        ),
        migrations.AddField(
            model_name='stationreturnstatus',
            name='month',
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='stationreturnstatus',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When the return was rejected', null=True),
        ),
        migrations.AddField(
            model_name='stationreturnstatus',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the return was submitted', null=True),
        ),
        migrations.AddField(
            model_name='stationreturnstatus',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='returnsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('imported', 'Imported Successfully'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='returnsubmission',
            index=models.Index(fields=['year', 'month'], name='returns_ret_year_3abce9_idx'),
        ),
        migrations.AddIndex(
            model_name='returnsubmission',
            index=models.Index(fields=['period'], name='returns_ret_period_18844c_idx'),
        ),
        migrations.AddIndex(
            model_name='returnsubmission',
            index=models.Index(fields=['prison_station', 'template'], name='returns_ret_prison__f1984c_idx'),
        ),
        migrations.AddIndex(
            model_name='stationreturnstatus',
            index=models.Index(fields=['year', 'month'], name='returns_sta_year_be4f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='stationreturnstatus',
            index=models.Index(fields=['period'], name='returns_sta_period_237f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='stationreturnstatus',
            index=models.Index(fields=['status'], name='returns_sta_status_106609_idx'),
        ),
        migrations.AddField(
            model_name='monthlysubmissiontracker',
            name='prison_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_trackers', to='prison.prisonstation'),
        ),
        migrations.AddField(
            model_name='returntypestatus',
            name='prison_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_type_statuses', to='prison.prisonstation'),
        ),
        migrations.AddField(
            model_name='returntypestatus',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='returns.returnsubmission'),
        ),
        migrations.AddField(
            model_name='returntypestatus',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_statuses', to='returns.returntemplate'),
        ),
        migrations.AddIndex(
            model_name='monthlysubmissiontracker',
            index=models.Index(fields=['year', 'month'], name='returns_mon_year_fbbf04_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlysubmissiontracker',
            index=models.Index(fields=['period'], name='returns_mon_period_2c5038_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlysubmissiontracker',
            unique_together={('prison_station', 'year', 'month', 'period')},
        ),
        migrations.AddIndex(
            model_name='returntypestatus',
            index=models.Index(fields=['year', 'month'], name='returns_ret_year_f6ed1b_idx'),
        ),
        migrations.AddIndex(
            model_name='returntypestatus',
            index=models.Index(fields=['period'], name='returns_ret_period_171a11_idx'),
        ),
        migrations.AddIndex(
            model_name='returntypestatus',
            index=models.Index(fields=['status'], name='returns_ret_status_12f48f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='returntypestatus',
            unique_together={('prison_station', 'template', 'period')},
        ),
    ]
