# Generated by Django 5.2.1 on 2026-09-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_monthlysubmissiontracker_returntypestatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returndata',
            options={'ordering': ['row_number']},
        ),
        migrations.AddField(
            model_name='returndata',
            name='row_number',
            field=models.PositiveIntegerField(default=0, help_text='Original row number from the file'),
        ),
        migrations.AddIndex(
            model_name='returndata',
            index=models.Index(fields=['submission', 'row_number'], name='returns_ret_submiss_87d268_idx'),
        ),
    ]
