# Generated by Django 5.2.1 on 2026-09-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, choices=[('southern', 'Southern Region'), ('northern', 'Northern Region'), ('eastern', 'Eastern Region'), ('western', 'Western Region')], help_text='Region permission (for regional admins)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Super Administrator'), ('admin', 'Prison Administrator'), ('reception', 'Reception Officer'), ('officer_in_charge', 'Officer in Charge'), ('station_officer', 'Station Officer'), ('visitor_attendant', 'Visitor Attendant'), ('medical', 'Medical Officer')], default='reception', max_length=20),
        ),
    ]
