# Generated by Django 5.2.1 on 2026-08-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Super Administrator'), ('admin', 'Prison Administrator'), ('reception', 'Reception Officer'), ('officer_in_charge', 'Officer in Charge'), ('station_officer', 'Station Officer'), ('visitor_attendant', 'Visitor Attendant'), ('medical', 'Medical Officer')], default='reception', max_length=20),
        ),
    ]
