# Generated by Django 5.2.1 on 2026-09-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_region_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_suspicious",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_login_user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="suspicious_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="rank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("warder", "Warder"),
                    ("sergeant", "Sergeant"),
                    ("gaoler", "Gaoler"),
                    ("inspector", "Inspector"),
                    ("supritendent", "Supritendent"),
                    ("acp", "ACP"),
                    ("dcp", "DCP"),
                    ("ict_officer", "ICT Officer"),
                    ("systems_analyst", "Systems Analyst"),
                    ("network_admin", "Network Administrator"),
                    ("security_analyst", "Security Analyst"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("southern", "Southern Region"),
                    ("northern", "Northern Region"),
                    ("eastern", "Eastern Region"),
                    ("central", "Central Region"),
                ],
                help_text="Region permission (for regional admins)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("superuser", "Super Administrator"),
                    ("admin", "Prison Administrator"),
                    ("reception", "Reception Officer"),
                    ("officer_in_charge", "Officer in Charge"),
                    ("station_officer", "Station Officer"),
                    ("visitor_attendant", "Visitor Attendant"),
                    ("medical", "Medical Officer"),
                    ("warden", "Warden"),
                    ("ict_personnel", "ICT Personnel"),
                ],
                default="reception",
                max_length=20,
            ),
        ),
    ]
