# Generated by Django 5.2.1 on 2026-08-13 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_region_fk'),
        ('prison', '0010_region_prisonstation_region_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='prison_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='prison.prisonstation'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(blank=True, choices=[('warder', 'Warder'), ('sergeant', 'Sergeant'), ('gaoler', 'Gaoler'), ('inspector', 'Inspector'), ('Supritendent', 'Supritendent'), ('ACP', 'ACP'), ('DCP', 'DCP')], max_length=20),
        ),
    ]
