# Generated by Django 5.2.1 on 2026-08-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of consecutive failed login attempts.', verbose_name='Failed Login Attempts'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='When set, the account cannot log in until ICT unlocks it.', verbose_name='Locked'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='require_password_reset',
            field=models.BooleanField(default=False, help_text="When set, ICT must reset this user's password before they can log in.", verbose_name='Require Password Reset'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Super Administrator'), ('admin', 'Prison Administrator'), ('reception', 'Reception Officer'), ('officer_in_charge', 'Officer in Charge'), ('station_officer', 'Station Officer'), ('visitor_attendant', 'Visitor Attendant'), ('medical', 'Medical Officer'), ('national_commissioner', 'Commissioner of Administration/HR (National)'), ('national_hr', 'National HR Officer'), ('regional_commanding_officer', 'Region Commanding Officer (RCO)'), ('regional_headquarters_officer', 'Region Headquarters Officer (RHO)'), ('regional_hr', 'Regional HR Officer'), ('station_hr', 'Station HR Officer'), ('training_wing_officer', 'Training Wing Officer'), ('commissioner_training_school', 'Commissioner of Training School'), ('ict_personnel', 'ICT Personnel')], default='reception', max_length=50),
        ),
    ]
