# Generated by Django 5.2.1 on 2026-08-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrisonStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Station Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Station Code')),
                ('location_address', models.CharField(blank=True, max_length=255, verbose_name='Location Address')),
                ('contact_number', models.CharField(blank=True, max_length=20, verbose_name='Contact Number')),
                ('capacity', models.PositiveIntegerField(default=100, verbose_name='Capacity')),
                ('date_established', models.DateField(verbose_name='Date Established')),
            ],
            options={
                'verbose_name': 'Prison Station',
                'verbose_name_plural': 'Prison Stations',
                'ordering': ['region__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Region Name')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='Region Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='When set, the account is locked and cannot be used to login until ICT resets it.', verbose_name='Locked'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='Must Change Password'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default_profile.jpg', null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(blank=True, choices=[('warder', 'Warder'), ('sergeant', 'Sergeant'), ('gaoler', 'Gaoler'), ('inspector', 'Inspector'), ('superintendent', 'Superintendent'), ('assistant_superintendent', 'Assistant Superintendent'), ('senior_superintendent', 'Senior Superintendent'), ('assistant_commissioner', 'Assistant Commissioner'), ('deputy_commissioner', 'Deputy Commissioner'), ('commissioner', 'Commissioner'), ('commissioner_general', 'Commissioner General')], max_length=50, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='require_password_reset',
            field=models.BooleanField(default=False, help_text='When set, the user must have their password reset by ICT personnel before logging in.', verbose_name='Require Password Reset'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('national_commissioner', 'Commissioner of Administration/HR (National)'), ('national_hr', 'National HR Officer'), ('regional_commanding_officer', 'Region Commanding Officer (RCO)'), ('regional_headquarters_officer', 'Region Headquarters Officer (RHO)'), ('regional_hr', 'Regional HR Officer'), ('station_hr', 'Station HR Officer'), ('training_wing_officer', 'Training Wing Officer'), ('commissioner_training_school', 'Commissioner of Training School'), ('ict_personnel', 'ICT Personnel'), ('superuser', 'Super Administrator'), ('admin', 'Prison Administrator'), ('reception', 'Reception Officer'), ('officer_in_charge', 'Officer in Charge'), ('station_officer', 'Station Officer'), ('visitor_attendant', 'Visitor Attendant'), ('medical', 'Medical Officer')], default='reception', max_length=50, verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='prison_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.prisonstation', verbose_name='Assigned Prison Station'),
        ),
        migrations.AddField(
            model_name='prisonstation',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='accounts.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Region scope, required for regional level roles.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.region', verbose_name='Assigned Region'),
        ),
    ]
