# Generated by Django 5.2.4 on 2026-05-21 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, db_index=True, unique=True),
                ),
                ("total_actions", models.IntegerField(default=0)),
                ("creates", models.IntegerField(default=0)),
                ("updates", models.IntegerField(default=0)),
                ("deletes", models.IntegerField(default=0)),
                ("logins", models.IntegerField(default=0)),
                ("unique_users", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Audit Log Summary",
                "verbose_name_plural": "Audit Log Summaries",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("PERMISSION_CHANGE", "Permission Change"),
                            ("ROLE_CHANGE", "Role Change"),
                            ("EXPORT", "Export/Download"),
                            ("PRINT", "Print"),
                            ("REPORT_GENERATE", "Report Generated"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                (
                    "object_str",
                    models.CharField(
                        help_text="String representation of the object at time of change",
                        max_length=500,
                    ),
                ),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                (
                    "changed_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of field names that were changed",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="User-provided reason for the change (if applicable)",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "permissions": [
                    ("view_audit_log", "Can view audit logs"),
                    ("export_audit_log", "Can export audit logs"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLogField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("field_type", models.CharField(max_length=50)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                (
                    "audit_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_changes",
                        to="audit.auditlog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Field",
                "verbose_name_plural": "Audit Log Fields",
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["-timestamp"], name="audit_audit_timesta_901180_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="audit_audit_user_id_ea8c9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["model_name", "-timestamp"],
                name="audit_audit_model_n_ad1f4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "-timestamp"], name="audit_audit_action_e33994_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="audit_audit_content_4c2ead_idx",
            ),
        ),
    ]
